#datasource
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/etsy_spider?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: MyPassword

server:
  port: 8080

